config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  get 'login' => 'user_sessions#new', :as => :login
  delete 'logout'  => 'user_sessions#destroy', :as => :logout


  resources :users, only: [:new, :create]
  resources :tasks
  resources :user_sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks

  acts_as_authentic do |c|
  end # the configuration block is optional
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  authenticate_with User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    # UserSession.find automatically uses persistence_token to find user
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.user
  end

  helper_method :current_user_session, :current_user
end

app/controllers/concerns/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Successfully created account!"
      redirect_to root_url
    else
      flash[:warning] = "Account creation failed: #{@user.errors.full_messages}"
      redirect_to new_user_path
    end
  end

  private


  def user_params
    params.require(:user).permit(
      :username,
      :email,
      :password,
      :password_confirmation,
      :first_name,
      :last_name,
      :title,
      :company,
      :phone
    )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to login_url unless current_user
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)

    if task.save
      flash[:notice] = 'Successfully created a task.'
      redirect_to tasks_path
    else
      flash[:warning] = "Failed to create task: #{task.errors.full_messages}"
      redirect_to new_task_path
    end
  end

  def edit
    task
  end

  def update
    if task.update(task_params)
      flash[:notice] = 'Successfully updated a task.'
      redirect_to tasks_path
    else
      flash[:warning] = "Failed to update task: #{task.errors.full_messages}"
    end

  end

  def destroy
    task.destroy

    redirect_to tasks_path
  end

  private

  def task
    @task ||= Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(
      :name,
      :due_at,
      :completed_at
    )
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(user_session_params)
    if @user_session.save
      flash[:notice] = "Welcome"
      redirect_to root_url
    else
      flash[:warning] = "Invalid Login"
      redirect_to action: :new
    end
  end

  def destroy
    current_user_session.destroy
    redirect_to new_user_session_url
  end

  private

  def user_session_params
    params.require(:user_session).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Home Page</h1>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'CRM JWON', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
      </ul>
      <% if current_user %>
      <%= render 'layouts/user_signed_in' %>
      <% else %>
      <%= render 'layouts/user_signed_out' %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_toolbar.html.erb
<div class="toolbar">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li><%= link_to 'Tasks', tasks_path %></li>
    </ul>
  </div>
</div>

app/views/layouts/_user_signed_in.html.erb
<ul class="nav navbar-nav navbar-right">
  <li><a href="#">Signed in as <%= current_user.username %></a></li>
  <li>
    <%= link_to logout_path, method: :delete do %>
      <span class="glyphicon glyphicon-log-out"></span> Logout
    <% end %>
  </li>
</ul>

app/views/layouts/_user_signed_out.html.erb
<ul class="nav navbar-nav navbar-right">
  <li>
    <%= link_to new_user_path do %>
      <span class="glyphicon glyphicon-user"></span> Sign Up
    <% end %>
  </li>

  <li>
    <%= link_to login_path do %>
      <span class="glyphicon glyphicon-log-in"></span> Login
    <% end %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrmJwon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <%= render 'layouts/toolbar' %>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/tasks/_toolbar.html.erb
<div class="pull-right">
  <%= link_to new_task_path do %>
    <span class="glyphicon glyphicon-plus"></span> New Task
  <% end %>
</div>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= form_for @task, url: { action: 'update' } do |f| %>
  <label for="name">name</label>
  <%= f.text_field :name, class: "form-control" %>
  <label for="due_at">due at</label>
  <%= f.date_field :due_at, class: "form-control" %>
  <button type="submit" name="button">Submit</button>
<% end %>

app/views/tasks/index.html.erb
<div class="container-fluid">
  <%= render 'tasks/toolbar' %>

  <h1>Tasks</h1>
  <ul class="list-group">
    <% @tasks.each do |task| %>
    <li class="task-row list-group-item">
      <div class="checkbox">
          <label>
            <input type="checkbox" name="complete-task" value="">
            <%= task.name %>
          </label>
          <div class="task">
            <%= button_to edit_task_path(task), method: :get, class: "btn btn-default btn-xs task-edit" do %>
              <span class="glyphicon glyphicon-edit"></span>
            <% end %>
            <%= button_to task, method: :delete, remote: true, class: "btn btn-default btn-xs task-edit" do %>
              <span class="glyphicon glyphicon-trash"></span>
            <% end %>
          </div>
      </div>
    </li>
    <% end %>
  </ul>

</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= form_for @task, url: {action: 'create'} do |f| %>
  <label for="name">name</label>
  <%= f.text_field :name, class: "form-control" %>
  <label for="due_at">due at</label>
  <%= f.date_field :due_at, class: "form-control" %>
  <button type="submit" name="button">Submit</button>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>
<div class="">
  <%= form_for @user_session, :url => user_sessions_path do |f| %>
    <label for="">username</label>
    <%= f.text_field :username, class: "form-control" %>
    <label for="">password</label>
    <%= f.password_field :password, class: "form-control" %>
    <button type="submit" name="button">Submit</button>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>New User</h1>
<div class="">
  <%= form_for @user, url: {action: 'create'} do |f| %>
    <label for="">username</label>
    <%= f.text_field :username, class: "form-control" %>
    <label for="">email</label>
    <%= f.email_field :email, class: "form-control" %>
    <label for="">password</label>
    <%= f.password_field :password, class: "form-control" %>
    <label for="">password confirmation</label>
    <%= f.password_field :password_confirmation, class: "form-control" %>
    <button type="submit" name="button">Submit</button>
  <% end %>
</div>